//go:build !ignore_autogenerated

/*
Copyright 2026 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockPoolSpec) DeepCopyInto(out *BlockPoolSpec) {
	*out = *in
	if in.Replicated != nil {
		in, out := &in.Replicated, &out.Replicated
		*out = new(ReplicatedSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ErasureCoded != nil {
		in, out := &in.ErasureCoded, &out.ErasureCoded
		*out = new(ErasureCodedSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockPoolSpec.
func (in *BlockPoolSpec) DeepCopy() *BlockPoolSpec {
	if in == nil {
		return nil
	}
	out := new(BlockPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CsiCephIntegrationSpec) DeepCopyInto(out *CsiCephIntegrationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CsiCephIntegrationSpec.
func (in *CsiCephIntegrationSpec) DeepCopy() *CsiCephIntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(CsiCephIntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DaemonCount) DeepCopyInto(out *DaemonCount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DaemonCount.
func (in *DaemonCount) DeepCopy() *DaemonCount {
	if in == nil {
		return nil
	}
	out := new(DaemonCount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicesStorageSpec) DeepCopyInto(out *DevicesStorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicesStorageSpec.
func (in *DevicesStorageSpec) DeepCopy() *DevicesStorageSpec {
	if in == nil {
		return nil
	}
	out := new(DevicesStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErasureCodedSpec) DeepCopyInto(out *ErasureCodedSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErasureCodedSpec.
func (in *ErasureCodedSpec) DeepCopy() *ErasureCodedSpec {
	if in == nil {
		return nil
	}
	out := new(ErasureCodedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesystemSpec) DeepCopyInto(out *FilesystemSpec) {
	*out = *in
	in.MetadataPool.DeepCopyInto(&out.MetadataPool)
	if in.DataPools != nil {
		in, out := &in.DataPools, &out.DataPools
		*out = make([]NamedPoolConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MetadataServer != nil {
		in, out := &in.MetadataServer, &out.MetadataServer
		*out = new(MetadataServerSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesystemSpec.
func (in *FilesystemSpec) DeepCopy() *FilesystemSpec {
	if in == nil {
		return nil
	}
	out := new(FilesystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySpec.
func (in *GatewaySpec) DeepCopy() *GatewaySpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMStorageSpec) DeepCopyInto(out *LVMStorageSpec) {
	*out = *in
	out.LVSize = in.LVSize.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMStorageSpec.
func (in *LVMStorageSpec) DeepCopy() *LVMStorageSpec {
	if in == nil {
		return nil
	}
	out := new(LVMStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataServerSpec) DeepCopyInto(out *MetadataServerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataServerSpec.
func (in *MetadataServerSpec) DeepCopy() *MetadataServerSpec {
	if in == nil {
		return nil
	}
	out := new(MetadataServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedPoolConfig) DeepCopyInto(out *NamedPoolConfig) {
	*out = *in
	in.PoolConfig.DeepCopyInto(&out.PoolConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedPoolConfig.
func (in *NamedPoolConfig) DeepCopy() *NamedPoolConfig {
	if in == nil {
		return nil
	}
	out := new(NamedPoolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreSpec) DeepCopyInto(out *ObjectStoreSpec) {
	*out = *in
	in.MetadataPool.DeepCopyInto(&out.MetadataPool)
	in.DataPool.DeepCopyInto(&out.DataPool)
	out.Gateway = in.Gateway
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreSpec.
func (in *ObjectStoreSpec) DeepCopy() *ObjectStoreSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolConfig) DeepCopyInto(out *PoolConfig) {
	*out = *in
	if in.Replicated != nil {
		in, out := &in.Replicated, &out.Replicated
		*out = new(ReplicatedSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ErasureCoded != nil {
		in, out := &in.ErasureCoded, &out.ErasureCoded
		*out = new(ErasureCodedSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolConfig.
func (in *PoolConfig) DeepCopy() *PoolConfig {
	if in == nil {
		return nil
	}
	out := new(PoolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedSpec) DeepCopyInto(out *ReplicatedSpec) {
	*out = *in
	if in.RequireSafeReplicaSize != nil {
		in, out := &in.RequireSafeReplicaSize, &out.RequireSafeReplicaSize
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedSpec.
func (in *ReplicatedSpec) DeepCopy() *ReplicatedSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicatedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SdsElasticCluster) DeepCopyInto(out *SdsElasticCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(SdsElasticClusterStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SdsElasticCluster.
func (in *SdsElasticCluster) DeepCopy() *SdsElasticCluster {
	if in == nil {
		return nil
	}
	out := new(SdsElasticCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SdsElasticCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SdsElasticClusterList) DeepCopyInto(out *SdsElasticClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SdsElasticCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SdsElasticClusterList.
func (in *SdsElasticClusterList) DeepCopy() *SdsElasticClusterList {
	if in == nil {
		return nil
	}
	out := new(SdsElasticClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SdsElasticClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SdsElasticClusterSpec) DeepCopyInto(out *SdsElasticClusterSpec) {
	*out = *in
	out.Network = in.Network
	out.Mon = in.Mon
	out.Mgr = in.Mgr
	in.Storage.DeepCopyInto(&out.Storage)
	if in.BlockPools != nil {
		in, out := &in.BlockPools, &out.BlockPools
		*out = make([]BlockPoolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Filesystems != nil {
		in, out := &in.Filesystems, &out.Filesystems
		*out = make([]FilesystemSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObjectStores != nil {
		in, out := &in.ObjectStores, &out.ObjectStores
		*out = make([]ObjectStoreSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CsiCephIntegration != nil {
		in, out := &in.CsiCephIntegration, &out.CsiCephIntegration
		*out = new(CsiCephIntegrationSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SdsElasticClusterSpec.
func (in *SdsElasticClusterSpec) DeepCopy() *SdsElasticClusterSpec {
	if in == nil {
		return nil
	}
	out := new(SdsElasticClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SdsElasticClusterStatus) DeepCopyInto(out *SdsElasticClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SdsElasticClusterStatus.
func (in *SdsElasticClusterStatus) DeepCopy() *SdsElasticClusterStatus {
	if in == nil {
		return nil
	}
	out := new(SdsElasticClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.LVM != nil {
		in, out := &in.LVM, &out.LVM
		*out = new(LVMStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = new(DevicesStorageSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}
