//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephVersionStatus) DeepCopyInto(out *CephVersionStatus) {
	*out = *in
	if in.UpgradeProgress != nil {
		in, out := &in.UpgradeProgress, &out.UpgradeProgress
		*out = new(UpgradeProgress)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephVersionStatus.
func (in *CephVersionStatus) DeepCopy() *CephVersionStatus {
	if in == nil {
		return nil
	}
	out := new(CephVersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticCluster) DeepCopyInto(out *ElasticCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(ElasticClusterStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticCluster.
func (in *ElasticCluster) DeepCopy() *ElasticCluster {
	if in == nil {
		return nil
	}
	out := new(ElasticCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticClusterCredential) DeepCopyInto(out *ElasticClusterCredential) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(ElasticClusterCredentialStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticClusterCredential.
func (in *ElasticClusterCredential) DeepCopy() *ElasticClusterCredential {
	if in == nil {
		return nil
	}
	out := new(ElasticClusterCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticClusterCredential) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticClusterCredentialList) DeepCopyInto(out *ElasticClusterCredentialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticClusterCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticClusterCredentialList.
func (in *ElasticClusterCredentialList) DeepCopy() *ElasticClusterCredentialList {
	if in == nil {
		return nil
	}
	out := new(ElasticClusterCredentialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticClusterCredentialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticClusterCredentialRef) DeepCopyInto(out *ElasticClusterCredentialRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticClusterCredentialRef.
func (in *ElasticClusterCredentialRef) DeepCopy() *ElasticClusterCredentialRef {
	if in == nil {
		return nil
	}
	out := new(ElasticClusterCredentialRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticClusterCredentialSpec) DeepCopyInto(out *ElasticClusterCredentialSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticClusterCredentialSpec.
func (in *ElasticClusterCredentialSpec) DeepCopy() *ElasticClusterCredentialSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticClusterCredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticClusterCredentialStatus) DeepCopyInto(out *ElasticClusterCredentialStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticClusterCredentialStatus.
func (in *ElasticClusterCredentialStatus) DeepCopy() *ElasticClusterCredentialStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticClusterCredentialStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticClusterList) DeepCopyInto(out *ElasticClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticClusterList.
func (in *ElasticClusterList) DeepCopy() *ElasticClusterList {
	if in == nil {
		return nil
	}
	out := new(ElasticClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticClusterNetwork) DeepCopyInto(out *ElasticClusterNetwork) {
	*out = *in
	if in.Public != nil {
		in, out := &in.Public, &out.Public
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticClusterNetwork.
func (in *ElasticClusterNetwork) DeepCopy() *ElasticClusterNetwork {
	if in == nil {
		return nil
	}
	out := new(ElasticClusterNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticClusterSpec) DeepCopyInto(out *ElasticClusterSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(ElasticClusterNetwork)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticClusterSpec.
func (in *ElasticClusterSpec) DeepCopy() *ElasticClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticClusterStatus) DeepCopyInto(out *ElasticClusterStatus) {
	*out = *in
	if in.MonEndpoints != nil {
		in, out := &in.MonEndpoints, &out.MonEndpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(ElasticClusterCredentialRef)
		**out = **in
	}
	if in.CephVersion != nil {
		in, out := &in.CephVersion, &out.CephVersion
		*out = new(CephVersionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Health != nil {
		in, out := &in.Health, &out.Health
		*out = new(CephHealthStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(CephCapacityStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.OSDs != nil {
		in, out := &in.OSDs, &out.OSDs
		*out = new(OSDStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Mons != nil {
		in, out := &in.Mons, &out.Mons
		*out = new(DaemonStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Mgrs != nil {
		in, out := &in.Mgrs, &out.Mgrs
		*out = new(DaemonStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CephTopology != nil {
		in, out := &in.CephTopology, &out.CephTopology
		*out = new(CephTopologyStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephHealthStatus) DeepCopyInto(out *CephHealthStatus) {
	*out = *in
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]CephHealthCheck, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephHealthStatus.
func (in *CephHealthStatus) DeepCopy() *CephHealthStatus {
	if in == nil {
		return nil
	}
	out := new(CephHealthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephHealthCheck) DeepCopyInto(out *CephHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephHealthCheck.
func (in *CephHealthCheck) DeepCopy() *CephHealthCheck {
	if in == nil {
		return nil
	}
	out := new(CephHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephCapacityStatus) DeepCopyInto(out *CephCapacityStatus) {
	*out = *in
	out.Total = in.Total.DeepCopy()
	out.Used = in.Used.DeepCopy()
	out.Available = in.Available.DeepCopy()
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephCapacityStatus.
func (in *CephCapacityStatus) DeepCopy() *CephCapacityStatus {
	if in == nil {
		return nil
	}
	out := new(CephCapacityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSDStatus) DeepCopyInto(out *OSDStatus) {
	*out = *in
	if in.ByVersion != nil {
		in, out := &in.ByVersion, &out.ByVersion
		*out = make([]DaemonVersionCount, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSDStatus.
func (in *OSDStatus) DeepCopy() *OSDStatus {
	if in == nil {
		return nil
	}
	out := new(OSDStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DaemonStatus) DeepCopyInto(out *DaemonStatus) {
	*out = *in
	if in.ByVersion != nil {
		in, out := &in.ByVersion, &out.ByVersion
		*out = make([]DaemonVersionCount, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DaemonStatus.
func (in *DaemonStatus) DeepCopy() *DaemonStatus {
	if in == nil {
		return nil
	}
	out := new(DaemonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DaemonVersionCount) DeepCopyInto(out *DaemonVersionCount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DaemonVersionCount.
func (in *DaemonVersionCount) DeepCopy() *DaemonVersionCount {
	if in == nil {
		return nil
	}
	out := new(DaemonVersionCount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephTopologyStatus) DeepCopyInto(out *CephTopologyStatus) {
	*out = *in
	if in.LastPromotedAt != nil {
		in, out := &in.LastPromotedAt, &out.LastPromotedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephTopologyStatus.
func (in *CephTopologyStatus) DeepCopy() *CephTopologyStatus {
	if in == nil {
		return nil
	}
	out := new(CephTopologyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticClusterStatus.
func (in *ElasticClusterStatus) DeepCopy() *ElasticClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticClusterStorageSpec) DeepCopyInto(out *ElasticClusterStorageSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.BlockDeviceSelector != nil {
		in, out := &in.BlockDeviceSelector, &out.BlockDeviceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticClusterStorageSpec.
func (in *ElasticClusterStorageSpec) DeepCopy() *ElasticClusterStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticClusterStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticStorageClass) DeepCopyInto(out *ElasticStorageClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(ElasticStorageClassStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticStorageClass.
func (in *ElasticStorageClass) DeepCopy() *ElasticStorageClass {
	if in == nil {
		return nil
	}
	out := new(ElasticStorageClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticStorageClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticStorageClassList) DeepCopyInto(out *ElasticStorageClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticStorageClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticStorageClassList.
func (in *ElasticStorageClassList) DeepCopy() *ElasticStorageClassList {
	if in == nil {
		return nil
	}
	out := new(ElasticStorageClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticStorageClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticStorageClassSpec) DeepCopyInto(out *ElasticStorageClassSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticStorageClassSpec.
func (in *ElasticStorageClassSpec) DeepCopy() *ElasticStorageClassSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticStorageClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticStorageClassStatus) DeepCopyInto(out *ElasticStorageClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticStorageClassStatus.
func (in *ElasticStorageClassStatus) DeepCopy() *ElasticStorageClassStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticStorageClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeProgress) DeepCopyInto(out *UpgradeProgress) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeProgress.
func (in *UpgradeProgress) DeepCopy() *UpgradeProgress {
	if in == nil {
		return nil
	}
	out := new(UpgradeProgress)
	in.DeepCopyInto(out)
	return out
}
