{{- if .Values.operatorCeph.registry }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Chart.Name }}-registrysecret
  namespace: {{ .Values.operatorCeph.namespace }}
  {{- include "helm_lib_module_labels" (list . (dict "app" .Chart.Name )) | nindent 2 }}
data:
  .dockerconfigjson: {{ .Values.operatorCeph.registry.dockercfg }}
{{- end }}
